

<!--       Project Name: Exploring the Data Science Survey Done By Kaggle (2017)              -->
<!--       Group Members:                                                                     -->
<!--                         1. Aditya Ramesh Kolhatkar                                       -->
<!--                         2. Om Anil Chaudhari                                             -->
<!--                         3. Ritisha Soni                                                  -->










<!-- 1. Welcome to the world of data science -->
<!-- Throughout the world of data science, there are many languages and tools that can be used to complete a given task. While you are often able to use whichever tool you prefer, it is often important for analysts to work with similar platforms so that they can share their code with one another. Learning what professionals in the data science industry use while at work can help you gain a better understanding of things that you may be asked to do in the future. -->

<!-- In this project, we are going to find out what tools and languages professionals use in their day-to-day work. Our data comes from the Kaggle Data Science Survey (https://www.kaggle.com/kaggle/kaggle-survey-2017)which includes responses from over 10,000 people that write code to analyze data in their daily work. -->


# Loading necessary packages
library(tidyverse)
# Loading the data
responses <- read_csv("C:/Users/adity/Desktop/R/kagglesurveynew.csv")
# Printing the first 10 rows
head(responses, 10)










<!-- 2. Using multiple tools -->
<!-- Now that we've loaded in the survey results, we want to focus on the tools and languages that the survey respondents use at work. -->


# Printing the first respondents' tools and languages
head(responses$WorkToolsSelect)
# Creating a new data frame called tools
tools <- responses
# Adding a new column to tools which splits the WorkToolsSelect column at the commas and unnests the new column
tools <- tools  %>% 
    mutate(work_tools = strsplit(WorkToolsSelect, ",")) %>%
    unnest(work_tools)
# Viewing the first 6 rows of tools
head(tools)










<!-- 3. Counting users of each tool -->
<!-- Now that we've split apart all of the tools used by each respondent, we can figure out which tools are the most popular. -->


# Creating a new data frame
tool_count <- tools
# Grouping the data by work_tools, calculate the number of responses in each group
tool_count <- tool_count  %>% 
    group_by(work_tools)  %>% 
    summarise(n = n())
# Sorting tool_count so that the most popular tools are at the top
tool_count <- tool_count %>%
    arrange(desc(n))
# Printing the first 6 results
head(tool_count)










<!-- 4. Plotting the most popular tools -->
<!-- Let's see how your favorite tools stack up against the rest. -->


# Creating a bar chart of the work_tools column. 
# Arranging the bars so that the tallest are on the far right
ggplot(tool_count, aes(x = reorder(work_tools, n), y = n)) + 
    geom_bar(stat = 'identity') +
# Rotating the bar labels 90 degrees
    theme(axis.text.x = element_text(angle = 90))










<!-- 5. The R vs Python debate -->
<!-- Within the field of data science, there is a lot of debate among professionals about whether R or Python should reign supreme. You can see from our last figure that R and Python are the two most commonly used languages, but it's possible that many respondents use both R and Python. Let's take a look at how many people use R, Python, and both tools. -->


# Creating a new data frame called debate_tools
debate_tools <- responses
# Creating a new column called language preference, based on the conditions specified in the Instructions
debate_tools <- debate_tools  %>% 
   mutate(language_preference = case_when(
        grepl("Python", WorkToolsSelect) & grepl("R", WorkToolsSelect) ~ "both",
        grepl("R", WorkToolsSelect) ~ "R",
        grepl("Python", WorkToolsSelect) ~ "Python",
        !(grepl("R", WorkToolsSelect) & grepl("Python", WorkToolsSelect)) ~ "neither"
       )
    )
# Printing the first 6 rows
head(debate_tools)










<!-- 6. Plotting R vs Python users -->
<!-- Now we just need to take a closer look at how many respondents use R, Python, and both! -->


# Creating a new data frame
debate_plot <- debate_tools
# Grouping by language preference and calculate number of responses
debate_plot <- debate_plot  %>% 
   group_by(language_preference)  %>% 
   summarise(n = n()) %>%
# Removing the row for users of "neither"
    filter(language_preference != "neither")
# Creating a bar chart
ggplot(debate_plot, aes(x = language_preference, y = n)) + 
    geom_bar(stat = 'identity')










<!-- 7. Language recommendations -->
<!-- It looks like the largest group of professionals program in both Python and R. But what happens when they are asked which language they recommend to new learners? Do R lovers always recommend R? -->


# Creating a new data frame called debate_tools
recommendations <- debate_tools
# Grouping by language_preference and then LanguageRecommendationSelect
recommendations <- recommendations  %>% 
    group_by(language_preference, LanguageRecommendationSelect)  %>% 
    summarise(n = n())
# Removing empty responses and include the top recommendations
recommendations <- recommendations %>%
    filter(row_number() <= 4)










<!-- 8. The most recommended language by the language used -->
<!-- Just one thing left. Let's graphically determine which languages are most recommended based on the language that a person uses. -->


# Creating a faceted bar plot
ggplot(recommendations, aes(x = LanguageRecommendationSelect, y = n)) +
    geom_bar(stat = "identity") +
    facet_wrap(~language_preference)











<!-- 9. The moral of the story -->
<!-- So we've made it to the end. We've found that Python is the most popular language used among Kaggle data scientists, but R users aren't far behind. And while Python users may highly recommend that new learners learn Python, would R users find the following statement TRUE or FALSE? -->

# Would R users find this statement TRUE or FALSE?
R_is_number_one = TRUE
 



